/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('vecTheming.view.MainView', {
    extend: 'Ext.container.Viewport',

    itemId: 'mainView',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'north',
                    height: 100,
                    html: '<h1>VEC Framework Components</h1>',
                    items: [
                        {
                            xtype: 'button',
                            text: 'MyButton'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'menuPanel',
                    ui: 'newpanel',
                    width: 150,
                    title: 'Examples',
                    items: [
                        {
                            xtype: 'treepanel',
                            border: false,
                            width: 150,
                            collapsed: false,
                            collapsible: false,
                            header: false,
                            overlapHeader: false,
                            title: 'Examples',
                            hideHeaders: true,
                            animate: true,
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        text: 'Panels',
                                        expanded: true,
                                        children: [
                                            {
                                                text: 'Basic Panel',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        text: 'Buttons',
                                        expanded: true,
                                        children: [
                                            {
                                                text: 'Primary Buttons',
                                                leaf: true
                                            },
                                            {
                                                text: 'Secundary Buttons',
                                                leaf: true
                                            },
                                            {
                                                text: 'Tertiary Buttons',
                                                leaf: true
                                            },
                                            {
                                                text: 'Main Menu Buttons',
                                                leaf: true
                                            },
                                            {
                                                text: 'Menu Buttons',
                                                leaf: true
                                            },
                                            
                                        ]
                                    },
                                    {
                                        text: 'Toolbars',
                                        expanded: true,
                                        children: [
                                            {
                                                text: 'Docked Toolbar',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        text: 'Tabs',
                                        expanded: true,
                                        children: [
                                            {
                                                text: 'Basic Tabs',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        text: 'Windows',
                                        expanded: true,
                                        children: [
                                            {
                                                text: 'Basic Window',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        text: 'Forms',
                                        expanded: true,
                                        children: [
                                            {
                                                text: 'Form Elements',
                                                leaf: true
                                            }
                                        ]
                                    }
                                ]
                            },
                            rootVisible: false,
                            useArrows: true,
                            viewConfig: {
                                listeners: {
                                    itemclick: {
                                        fn: me.onViewItemClick,
                                        scope: me
                                    }
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    id: 'contentPanel',
                    itemId: 'contentPanel',
                    layout: {
                        type: 'card'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'basicPanel',
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            title: 'Basic Panel',
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    height: 100,
                                    html: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                                    width: 350,
                                    title: 'My Panel'
                                },
                                {
                                    xtype: 'panel',
                                    height: 100,
                                    html: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                                    width: 350,
                                    title: 'My Panel'
                                },
                                {
                                    xtype: 'panel',
                                    height: 100,
                                    html: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                                    width: 350,
                                    title: 'My Panel'
                                },
                                {
                                    xtype: 'panel',
                                    height: 100,
                                    html: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                                    width: 350,
                                    title: 'My Panel'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'primaryButtons',
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            title: 'Primary Buttons',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: 'disabled',
                                    listeners: {
                                        change: {
                                            fn: me.onCheckboxfieldChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_one',
                                    text: 'Checkout'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_two',
                                    text: 'See Details'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_three',
                                    text: 'find all links'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'secundaryButtons',
                            width: 100,
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            title: 'Secundary Buttons',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: 'disabled',
                                    listeners: {
                                        change: {
                                            fn: me.onCheckboxfieldChange1,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_one1',
                                    width: 100,
                                    text: 'Checkout'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_two1',
                                    width: 150,
                                    text: 'See Details'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_three1',
                                    text: 'find all links'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'tertiaryButtons',
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            title: 'Tertiary Buttons',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: 'disabled',
                                    listeners: {
                                        change: {
                                            fn: me.onCheckboxfieldChange11,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_one2',
                                    text: 'Checkout'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_two2',
                                    text: 'See Details'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_three2',
                                    text: 'find all links'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'mainMenuButtons',
                            title: 'Main Menu Buttons',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Contact Us View'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'menuButtons',
                            title: 'Menu Buttons',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Contact Us View'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'dockedToolbar',
                            title: 'Docked Toolbar',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Contact Us View'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'basicTabs',
                            layout: {
                                pack: 'center',
                                type: 'hbox'
                            },
                            title: 'Basic Tabs',
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    width: 450,
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            html: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                                            title: 'DESCRIPTION'
                                        },
                                        {
                                            xtype: 'panel',
                                            html: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed risus neque, mollis id auctor eget, aliquet vel augue. Sed egestas fermentum tempus. Praesent hendrerit eros et enim laoreet suscipit. Nam diam ante, ullamcorper id congue non, accumsan non augue. Aliquam non libero augue, vitae molestie orci. Nulla ac enim nec velit rhoncus venenatis. Aenean orci quam, eleifend ut aliquam iaculis, pellentesque ut arcu. Suspendisse lobortis commodo magna, vitae sodales orci luctus vestibulum. Cras eget ipsum sapien, vel dapibus metus. Etiam sed augue sit amet massa commodo commodo. Nam pellentesque dapibus ipsum. Proin eget malesuada magna. Curabitur elit diam, pellentesque id fermentum eget, congue ultricies nibh. Nunc tincidunt sem at diam porta tincidunt. Suspendisse fringilla felis in lectus blandit vulputate. Suspendisse mollis ipsum nec ante congue ut porttitor nunc bibendum. Maecenas mollis sem non justo iaculis vitae consequat augue pulvinar. Sed aliquet malesuada lobortis. Maecenas malesuada eros sed erat ultricies eleifend. Nulla facilisi. Pellentesque pharetra molestie mollis. Aenean venenatis tempus urna, quis convallis quam cursus eget.',
                                            title: 'DESIGN'
                                        },
                                        {
                                            xtype: 'panel',
                                            html: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                                            title: 'MARKUP'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'basicWindows',
                            title: 'Basic Windows'
                        },
                        {
                            xtype: 'panel',
                            itemId: 'formElements',
                            title: 'Form Elements',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    title: 'My Form'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onViewItemClick: function(dataview, record, item, index, e, eOpts) {
        //console.log(index);
        var content = Ext.getCmp('contentPanel');
        var activeItem = 0;
        switch(index)
        {
            case 1:
              activeItem = 0;
              break;
            case 3:
              activeItem = 1;
              break;
            case 4:
              activeItem = 2;
              break;
            case 5:
              activeItem = 3;
              break;
            case 6:
              activeItem = 4;
              break;
            case 7:
              activeItem = 5;
              break;
            case 9:
              activeItem = 6;
              break;
            case 11:
              activeItem = 7;
              break;
            case 13:
              activeItem = 8;
              break;
            case 15:
              activeItem = 9;
              break;
        }

        content.layout.setActiveItem(activeItem);
    },

    onCheckboxfieldChange: function(field, newValue, oldValue, eOpts) {
        //console.log(field.checked);
        var btone = Ext.getCmp('btn_one');
        var bttwo = Ext.getCmp('btn_two');
        var btthree = Ext.getCmp('btn_three');
        if(field.checked===true){
            btone.setDisabled(true);
            bttwo.setDisabled(true);
            btthree.setDisabled(true);
        }else{
            btone.setDisabled(false);
            bttwo.setDisabled(false);
            btthree.setDisabled(false);
        }
    },

    onCheckboxfieldChange1: function(field, newValue, oldValue, eOpts) {
        //console.log(field.checked);
        var btone = Ext.getCmp('btn_one1');
        var bttwo = Ext.getCmp('btn_two1');
        var btthree = Ext.getCmp('btn_three1');
        if(field.checked===true){
            btone.setDisabled(true);
            bttwo.setDisabled(true);
            btthree.setDisabled(true);
        }else{
            btone.setDisabled(false);
            bttwo.setDisabled(false);
            btthree.setDisabled(false);
        }
    },

    onCheckboxfieldChange11: function(field, newValue, oldValue, eOpts) {
        //console.log(field.checked);
        var btone = Ext.getCmp('btn_one2');
        var bttwo = Ext.getCmp('btn_two2');
        var btthree = Ext.getCmp('btn_three2');
        if(field.checked===true){
            btone.setDisabled(true);
            bttwo.setDisabled(true);
            btthree.setDisabled(true);
        }else{
            btone.setDisabled(false);
            bttwo.setDisabled(false);
            btthree.setDisabled(false);
        }
    }

});